### ISSUE TITLE
Arch安装后无法使用

### ISSUE THREAD

**Issue by YumeMichi** [askme765cs/Wine-QQ#7]
已经按照wiki安装好wine和winetricks，执行install.sh后提示安装成功，但是依然找不到快捷方式，手动执行qq.sh第一次可以运行起来，关掉后再次运行就没反应了

**Comment by askme765cs** [comment]
是否以root权限执行了install.sh?可重启后再打开试试

**Comment by leixd1994** [comment]
我也遇到这个问题。   解决办法：直接自己手动建立桌面快捷方式。   参考我的自己建一个就行了
leixd@lei-Ubuntu:~$ cat /usr/share/applications/qq.desktop 
[Desktop Entry]
Name=QQ
GenericName=QQ
X-GNOME-FullName=QQ
Comment=QQ
Exec=sh /media/leixd/OtherSoftware/Wine-QQ-master/Wine-QQ8.9.2/qq.sh
Icon=/media/leixd/OtherSoftware/Wine-QQ-master/Wine-QQ8.9.2/icon/QQ.png
Terminal=false
Type=Application
Categories=GNOME;System;Filesystem;Settings
Keywords=Partition;
StartupNotify=true

**Comment by YumeMichi** [comment]
时不时会失效 有时候得运行几次才会弹出来

**Comment by YumeMichi** [comment]
但是每几分钟就崩一次=。=
![](http://i.imgur.com/o31ua2H.png)

**Comment by leixd1994** [comment]
在Ubuntu 16.04 下没有问题

**Comment by YumeMichi** [comment]
试了一下公司跟家里的电脑都是一会儿就崩，系统都是Arch

**Comment by leixd1994** [comment]
你是装的wine-2.0.1 stable  这个版本的Wine么？   @YumeMichi

**Comment by YumeMichi** [comment]
@leixd1994 仓库里是2.10.1的版本，没有另外去编译旧版的

**Comment by leixd1994** [comment]
官网上的内容，可以看到2.10使开发版（Development），当然不稳定容易崩溃了
Latest Releases
Stable:
Wine 2.0.1 (shortlog)
Development:
Wine 2.10 (shortlog)

@YumeMichi

**Comment by leixd1994** [comment]
https://www.winehq.org/download   可以在这里根据你的系统下载安装2.0.1稳定版的Wine  @YumeMichi

**Comment by YumeMichi** [comment]
好的多谢

**Comment by YumeMichi** [comment]
还是崩 尴尬
```
ikke@YumeMichi:~ [fg: 1] % wine --version
wine-2.0.1
```

**Comment by leixd1994** [comment]
![screenshot from 2017-06-15 14-03-51](https://user-images.githubusercontent.com/23328517/27167460-8580358e-51d3-11e7-980c-115c26d947ad.png)
 Ubuntu下挺正常的o(╯□╰)o  难道真是系统的原因  o(╯□╰)o

**Comment by askme765cs** [comment]
已经修复在系统应用菜单中显示的问题和启动问题
我构建项目的版本wine-2.9，也是archlinux,可以尝试升级一下

**Comment by leixd1994** [comment]
辛苦了～   顶 @askme765cs
